version: 0.0
os: linux
files:
  - source: /
    destination: /var/api/
hooks:
  Install:
    - location: scripts/npm.sh
      runas: root     
  AfterInstall:
    - location: scripts/npm-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/npm-start.sh
      runas: root
      timeout: 300
